version: '3.5'
services:
  app:
    build: .
    ports:
      - "6565:6565"
      - "8080:8080"
    env_file: .env
    extra_hosts:
      - host.docker.internal:host-gateway
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: http://localhost:3100/loki/api/v1/push
    #     mode: non-blocking
    #     max-buffer-size: 4m
    #     loki-retries: "3"
